spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related to QA APIs"
  contactDetails:
    name: "Amith Kashyap QA"
    email: "amith_qa@gmail.com"
  onCallSupport:
    - (1234)56789
    - (0987)654321