server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - "prod"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related to Dev APIs"
  contactDetails:
    name: "Amith Kashyap Dev"
    email: "amith_dev@gmail.com"
  onCallSupport:
    - (1234)56789
    - (0987)654321